In [1]:
## Calculate the betas for a regression of two X variables onto a Y vector using matrix formulation using module "numpy" (3 betas - 1 beta for the intercept, and 2 betas for the two X predictor variables)

In [2]:
# Import numpy module
import numpy as np

# Consider the Y vector to be a variable labeled "Missed Days at Work";
# there are 12 rows (objects)

Y=np.array([1,0,1,4,3,2,5,6,9,13,15,16])
print(Y)

[ 1  0  1  4  3  2  5  6  9 13 15 16]


In [3]:
# Consider column 2 of X to be a variable labeled "Attitude Toward Work" - a 1 to 13 point
# rating scale where 1 is extremely favorable and 13 is extremely unfavorable;
# and consider column 3 of X to be a variable labeled "Years in Present Position";
# X has 12 rows and 3 columns;  the first column is all 1's

X=np.array([[1,1,1],
           [1,2,1],
           [1,2,2],
           [1,3,2],
           [1,5,4],
           [1,5,6],
           [1,6,5],
           [1,7,4],
           [1,10,8],
           [1,11,7],
           [1,11,9],
           [1,12,10]])
print(X)

[[ 1  1  1]
 [ 1  2  1]
 [ 1  2  2]
 [ 1  3  2]
 [ 1  5  4]
 [ 1  5  6]
 [ 1  6  5]
 [ 1  7  4]
 [ 1 10  8]
 [ 1 11  7]
 [ 1 11  9]
 [ 1 12 10]]


In [4]:
# Dimensions of Y: a 12 by 1 vector
Y.shape

(12,)

In [5]:
# Dimensions of X: a 12 by 3 matrix
X.shape

(12, 3)

In [6]:
# Transpose of X
# Here I am taking Transpose as X-Transpose
Transpose=X.T
print(Transpose)
Transpose.shape

[[ 1  1  1  1  1  1  1  1  1  1  1  1]
 [ 1  2  2  3  5  5  6  7 10 11 11 12]
 [ 1  1  2  2  4  6  5  4  8  7  9 10]]


(3, 12)

In [7]:
# Multiplication of X-Transpose and X
# Here I am taking Transpose_M as multiplication of X-Transpose
Transpose_M=Transpose@X
print(Transpose_M)
Transpose_M.shape

[[ 12  75  59]
 [ 75 639 497]
 [ 59 497 397]]


(3, 3)

In [8]:
# In this step we are doing Matrix Inverse
Matrix_I=np.linalg.inv(Transpose_M)
print(Matrix_I)

[[ 0.3169944  -0.0214686  -0.02023368]
 [-0.0214686   0.06093854 -0.07309775]
 [-0.02023368 -0.07309775  0.09703619]]


In [9]:
#calculating betas
#for finding betas we have to multiple Matrix Inverse and X Transpose and Y
Betas=Matrix_I@Transpose@Y
print(Betas)
Betas.shape

[-2.2630379   1.54972927 -0.2385295 ]


(3,)

In [10]:
#for Calculating Betas
#There is another way of finding betas
#betas=np.linalg.inv((Transpose)@X)@(Transpose)@Y
#print(betas)
#betas.shape

[-2.2630379   1.54972927 -0.2385295 ]


In [11]:
#Calculating the beta values

Beta_0=Betas[0]
print("Beta 0 :", Beta_0)

Beta_1=Betas[1]
print("Beta 1 :", Beta_1)

Beta_2=Betas[2]
print("Beta 2 :", Beta_2)


Beta 0 : -2.263037902536326
Beta 1 : 1.5497292675976115
Beta 2 : -0.2385294955827928
